fragment SiteSettingsParts on SiteSettings {
  __typename
  contact {
    __typename
    email
    phone
    address
  }
  hero {
    __typename
    title
    subtitle
    backgroundImage
  }
}

fragment MenuCategoriesParts on MenuCategories {
  __typename
  name
  description
  order
}

fragment MenuItemsParts on MenuItems {
  __typename
  name
  description
  category {
    ... on MenuCategories {
      __typename
      name
      description
      order
    }
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
  }
  image
  featured
  sections {
    __typename
    title
    items
  }
  boxMaxItemsPerBox
}

fragment TestimonialsParts on Testimonials {
  __typename
  name
  company
  content
  rating
  avatar
}

fragment GalleryImagesParts on GalleryImages {
  __typename
  src
  alt
  caption
  album
}

fragment TranslationsParts on Translations {
  __typename
  language
  nav {
    __typename
    home
    menu
    gallery
    testimonials
    contact
    orderNow
  }
  hero {
    __typename
    title
    subtitle
    viewMenu
  }
  about {
    __typename
    title
    description1
    description2
  }
  aviationMessage {
    __typename
    title
  }
  menu {
    __typename
    title
    subtitle
    heroTitle
    heroSubtitle
    customMenuTitle
    customMenuDescription
    requestCustomMenu
    qualityTitle
    qualityDescription1
    qualityDescription2
    boxOptions {
      __typename
      selectItemsToAdd
      addItemsPrefix
      itemSingular
      itemPlural
      toastAddedPrefix
      toastFrom
      perOptionNotePlaceholder
      validationSelectAtLeastOne
      addToOrder
      selectedItemsLabel
      inlineAdded
      selectionHeader
      numberOfBoxesLabel
      quantityLabel
      chooseUpTo
      reachedMax
      clearSelections
    }
  }
  testimonials {
    __typename
    title
    subtitle
    viewAll
    joinClients
    experienceDescription
  }
  gallery {
    __typename
    title
    subtitle
    prev
    next
  }
  common {
    __typename
    loading
    error
    tryAgain
    close
    save
    cancel
    confirm
    delete
    edit
    add
    remove
    search
    filter
    sort
    next
    previous
    page
    of
    results
    noResults
    selectLanguage
  }
  meta {
    __typename
    homeTitle
    homeDescription
    menuTitle
    menuDescription
    testimonialsTitle
    testimonialsDescription
    contactTitle
    contactDescription
    ogImage
  }
  contact {
    __typename
    title
    subtitle
    getInTouch
    description
    phone
    email
    address
    hours
    hoursText
    fastResponse
    name
    phoneLabel
    deliveryDate
    wheelsUpTime
    specialRequests
    specialRequestsPlaceholder
    submitInquiry
    submitting
    thankYou
    thankYouMessage
    sendAnother
    phoneMain
    phoneDirect
    emailAddress
    addressLine1
    addressLine2
    addressCountry
  }
  footer {
    __typename
    airportsServed
    emailDescription
    quickLinks
    legal
    privacyPolicy
    termsOfService
    copyright
  }
  howItWorks {
    __typename
    title
    subtitle
  }
  page {
    __typename
    airportKMSP
    airportKSTP
    airportKFCM
    airportKANE
  }
}
